name: Build and deploy on server

on:
  push

env:
  DIRECTORY: "${{ vars.DIRECTORY }}/${{ github.event.repository.name }}"

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Create .env file
        run: |
          echo "${{ secrets.ENVS }}" > .env

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  setup-ssh:
    runs-on: ubuntu-latest
    needs: checkout-code

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Save SSH and environment info
        run: |
          echo "${{ secrets.SERVER_USER }}" > server_user
          echo "${{ secrets.SERVER_HOST }}" > server_host
          echo "${{ env.DIRECTORY }}" > directory

      - name: Upload SSH and environment info
        uses: actions/upload-artifact@v3
        with:
          name: ssh-info
          path: |
            server_user
            server_host
            directory

  deploy-on-server:
    runs-on: ubuntu-latest
    needs: setup-ssh

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Download SSH and environment info
        uses: actions/download-artifact@v3
        with:
          name: ssh-info
          path: .

      - name: Deploy on Server
        run: |
          SERVER_USER=$(cat server_user)
          SERVER_HOST=$(cat server_host)
          DIRECTORY=$(cat directory)

          echo $DIRECTORY
          ssh -t $SERVER_USER@$SERVER_HOST << EOF
            rm -rf $DIRECTORY && mkdir -p $DIRECTORY
          EOF
          scp -r * $SERVER_USER@$SERVER_HOST:$DIRECTORY
          scp .env $SERVER_USER@$SERVER_HOST:$DIRECTORY/.env
          ssh -t $SERVER_USER@$SERVER_HOST << EOF
            echo "Starting deployment process..."
            cd $DIRECTORY
            sh "$DIRECTORY/deploy.sh"
            echo "Deployment successful, cleaning up directory..."
            rm -rf $DIRECTORY
          EOF
