name: Clone repository and deploy on server

on:
  push

env:
  DIRECTORY: "${{ vars.DIRECTORY }}/${{ github.event.repository.name }}"

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

  deploy-on-server:
    runs-on: ubuntu-latest
    needs: setup-ssh

    steps:
      - name: Deploy on Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DIRECTORY: ${{ env.DIRECTORY }}

        run: |
          echo $DIRECTORY
          ssh -t $SERVER_USER@$SERVER_HOST << EOF
            if [ -d "$DIRECTORY" ]; then
              rm -rf $DIRECTORY
            fi
            mkdir -p $DIRECTORY
            cd $DIRECTORY
            git clone https://github.com/${{ github.repository }} .
            echo "${{ secrets.ENVS }}" > .env
            sh deploy.sh
            echo "Deployment successful, cleaning up directory..."
            rm -rf $DIRECTORY
          EOF
