name: Prebuild
on: push
jobs:
  lint:
    uses: ./.github/workflows/test.yml
  test:
    uses: ./.github/workflows/test.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/environment.yml
      - name: Build
        run: npm run build
