name: Cache Environment
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: 'lts'
        type: string
      os:
        description: 'Operating System'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  cache-environment:
    runs-on: ${{ inputs.os }}
    outputs:
      cache-key: ${{ steps.set-cache-key.outputs.cache-key }}
      package-name: ${{ steps.extract-package-json.outputs.package-name }}
      package-version: ${{ steps.extract-package-json.outputs.package-version }}
      os: ${{ inputs.os }}
      node-version: ${{ inputs.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract name and version from package.json
        id: extract-package-json
        run: |
          NAME=$(jq -r '.name' package.json)
          VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_NAME=$NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
      

      - name: Set cache key
        id: set-cache-key
        run: |
          echo "cache-key=${{ runner.os }}-${{ inputs.node-version }}-${{ inputs.cache-key }}-${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}" >> $GITHUB_ENV
      

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.cache-key }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}
            ${{ runner.os }}-${{ inputs.node-version }}-${{ env.PACKAGE_NAME }}
            ${{ runner.os }}-${{ inputs.node-version }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Save node_modules as artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: |
            ~/.npm/
            node_modules/
