name: Prebuild
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - name: Lint
        uses: ./.github/workflows/lint.yml
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Test
        uses: ./.github/workflows/test.yml
